const data = [
    { title: '1. Present time', ratings: 5, body:'explanation', key: 1},
    { title: '2. Future time', ratings: 5, body:'explanation', key: 1},
    { title: '3. Past time', ratings: 5, body:'explanation', key: 1},
    { title: '4. Present perfect', ratings: 5, body:'explanation', key: 1},
    { title: '5. Consolidation 1', ratings: 5, body:'explanation', key: 1},
    { title: '6. Passive 1', ratings: 5, body:'explanation', key: 1},
    { title: '7. Passive 2', ratings: 5, body:'explanation', key: 1},
    { title: '8. Conditionals', ratings: 5, body:'explanation', key: 1},
    { title: '9. Unreal time and subjunctives', ratings: 5, body:'explanation', key: 1},
    { title: '10. Consolidation 2', ratings: 5, body:'explanation', key: 1},
    { title: '11. Modals: present and future', ratings: 5, body:'explanation', key: 1},
    { title: '12. Modals: past', ratings: 5, body:'explanation', key: 1},
    { title: '13. Inversion', ratings: 5, body:'explanation', key: 1},
    { title: '14. Emphasis', ratings: 5, body:'explanation', key: 1},
    { title: '15. Consolidation 3', ratings: 5, body:'explanation', key: 1},
    { title: '16. Reported speech', ratings: 5, body:'explanation', key: 1},
    { title: '17. Articles', ratings: 5, body:'explanation', key: 1},
    { title: '18. Relative and non-finite clauses', ratings: 5, body:'explanation', key: 1},
    { title: '19. Verbs + infinitive or -ing', ratings: 5, body:'explanation', key: 1},
    { title: '20. Consolidation 4', ratings: 5, body:'explanation', key: 1},
    { title: '21. Verbs + prepositions', ratings: 5, body:'explanation', key: 1},
    { title: '22. Prepositions', ratings: 5, body:'explanation', key: 1},
    { title: '23. Phrasal verbs 1', ratings: 5, body:'explanation', key: 1},
    { title: '24. Phrasal verbs 2', ratings: 5, body:'explanation', key: 1},
    { title: '25. Phrasal verbs 3', ratings: 5, body:'explanation', key: 1},
    { title: '26. Consolidation 5', ratings: 5, body:'explanation', key: 1},
    { title: '27. Linking words and phrases', ratings: 5, body:'explanation', key: 1},
    { title: '28. Punctuation and spelling', ratings: 5, body:'explanation', key: 1},
    { title: '29. Consolidation 6', ratings: 5, body:'explanation', key: 1},
    { title: '30. Further practice', ratings: 5, body:'explanation', key: 1}
]

export default data