export default appIcons = {
  icon_bienbao: require("../assets/icons/icon_bienbao.png"),
  icon_book: require("../assets/icons/icon_book.png"),
  icon_law: require("../assets/icons/icon_law.png"),
  icon_test: require("../assets/icons/icon_test.png"),
  icon_tips: require("../assets/icons/icon_tips.png"),
  icon_wrong: require("../assets/icons/icon_wrong.png"),
  chuyenhuong: require("../assets/icons/chuyenhuong.png"),
  dungxe: require("../assets/icons/dungxe.png"),
  duongcam: require("../assets/icons/duongcam.png"),
  giaytoxe: require("../assets/icons/giaytoxe.png"),
  hieulenh: require("../assets/icons/hieulenh.png"),
  khac: require("../assets/icons/khac.png"),
  nongdocon: require("../assets/icons/nongdocon.png"),
  tocdo: require("../assets/icons/tocdo.png"),
  traffic: require("../assets/icons/traffic.png"),
  ttb: require("../assets/icons/ttb.png"),
  uutien: require("../assets/icons/uutien.png"),
  vanchuyen: require("../assets/icons/vanchuyen.png"),
  menu: require("../assets/icons/open-menu.png"),
  back: require("../assets/icons/back.png"),
  next: require("../assets/icons/next.png"),
  partner: require("../assets/icons/partners.png"),
  signage: require("../assets/icons/signage.png"),
  motor: require("../assets/icons/motorcycle.png"),
  checklist: require("../assets/icons/checklist.png"),
};
