import { StyleSheet, Dimensions } from 'react-native'; 
const WIDTH=Dimensions.get('window').width;
const HEIGHT=Dimensions.get('window').height;
const styles = StyleSheet.create({
    btnDetail:{
        backgroundColor:'#ff5e00',
        alignItems:'center',
        borderRadius:20,
        width:150
    },
    containers:{
        top:10,
        height:HEIGHT,
        width:WIDTH*0.8,
        left:WIDTH/6
    },
    card:{
        width:WIDTH*0.7,
        height:HEIGHT*0.7,
        borderRadius:10,
        alignItems:'center',
    },
    viewCard:{
        width:WIDTH*0.7,
        height:HEIGHT*0.7,
        borderRadius:10,
        alignItems:'center',
        position:'absolute',
        zIndex:0
    },
    container:{
        width:WIDTH,
        height:HEIGHT,
    },
    viewBtn:{
        alignItems:'center',
        position:'absolute',
        top:HEIGHT*0.69,
        left:65,
        zIndex:2,
    },
    viewImg:{
        alignItems:'center',
    },
    img:{
        width:150,
        height:150,
        borderRadius:100,
        borderWidth:1,
        borderColor:'#80808085'
    },
    viewTool:{
        flexDirection:'column',
        backgroundColor:'#ff5e00',
        width:40,
        alignItems:'center',
        padding:5,
        position:'absolute',
        right:20,
        borderRadius:6,
        zIndex:2,
        top:100
    },
    iconTool:{
        color:'white',
        fontSize:12,
    },
    viewIcon:{
        borderRadius:30,
        borderWidth:1,
        borderColor:'white',
        padding:6,
        marginTop:5,
        marginBottom:5,
    },
})

export default styles; 